import "primevue/resources/themes/saga-blue/theme.css";
import "primevue/resources/primevue.min.css";
import "primeicons/primeicons.css";
import "primevue/resources/themes/bootstrap4-light-blue/theme.css";
import "/node_modules/primeflex/primeflex.css";
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import PrimeVue from "primevue/config";
import MenuBar from "primevue/menubar";
import Button from "primevue/button";
import Galleria from 'primevue/galleria';
import Card from 'primevue/card';
import Image from 'primevue/image';
import Avatar from "primevue/avatar";
import Menu from "primevue/menu";
import InputText from "primevue/inputtext";
import Password from "primevue/password";
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Skeleton from 'primevue/skeleton';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import Chip from 'primevue/chip';
import Calendar from 'primevue/calendar';
import Textarea from 'primevue/textarea';
import Chips from 'primevue/chips';
import FileUpload from 'primevue/fileupload';
import Dropdown from 'primevue/dropdown';
import Inplace from 'primevue/inplace';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';
import dayjs from "dayjs";

const app = createApp(App);
app.use(store);
app.use(router);
app.use(PrimeVue);
app.use(ToastService);
app.config.globalProperties.$dayjs = dayjs;
app.component('Menubar',MenuBar);
app.component('Button', Button);
app.component('Galleria', Galleria);
app.component('Card', Card);
app.component('Image', Image);
app.component('Avatar', Avatar);
app.component('Menu', Menu);
app.component('InputText', InputText);
app.component('Password', Password);
app.component('DataTable', DataTable);
app.component('Column', Column);
app.component('Skeleton', Skeleton);
app.component("Toast", Toast);
app.component("Chip", Chip);
app.component("Calendar", Calendar);
app.component("Textarea", Textarea);
app.component("Chips",Chips);
app.component("FileUpload", FileUpload);
app.component("Dropdown", Dropdown);
app.component("Inplace", Inplace);
app.component("TabView", TabView);
app.component("TabPanel", TabPanel);


app.mount('#app');

export {app};